import { Card, CardBody, Text } from "@chakra-ui/react";
import Head from "next/head";

export default function Landing() {
    return (
        <div>
            <Head>
                <title>Task.ly</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Card size="lg" colorScheme="gray" variant="filled">
                    <CardBody>
                        <Text>
                            This is some sample text
                        </Text>
                    </CardBody>
                </Card>
            </main>
            
        </div>
    );
}